# Running "docker-compose up" (active process)
# or "docker-compose start" (background process)
# will setup our development database and backend API
#
# Use docker-compose up <service-name> will launch the services individually
#
# One can connect to the database using your DB client
# (IntelliJ, DataGrip, pqadmin, psql, ...),
# using the following parameters (see: application.properties):
#   url = jdbc:postgresql://localhost:15432/prbed-vliegmaatschappij
#   username = prbed-vliegmaatschappij
#   password = prbed-vliegmaatschappij
version: "3.7"
services:
  api:
    container_name: prbed-backend-team-dit
    image: ghcr.io/huict/prbed-2122-v2c-teamdit/prbed-teamdit:github-workflows
    depends_on:
      - db
    ports:
      - '8080:8080'
    env_file:
      - .env

  db:
    container_name: prbed-postgres-team-dit
    build: development/db
    ports:
      - "15432:5432"
    env_file:
      - .env
    volumes:
      - "./data:/var/data/db"